name: ETL Pipeline Demo
on:
  push:
    branches:
      - main

jobs:
  extract-data-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: show python version
        run: python --version     

      - name: Install required depencies
        run: pip install pandas

      - name: Run extract.py
        run: python extract.py        


  transform-data-job:
    runs-on: ubuntu-latest
    needs: extract-data-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run transform.py
        run: python transform.py

  load-data-job:
    runs-on: ubuntu-latest
    needs: transform-data-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run load.py
        run: python load.py
